name: CD for EMTC

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release Tasks
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get latest tag
        id: get_tag
        run: |
          git pull --tags --force
          echo "tag=$(git describe --abbrev=0 --tags 2>/dev/null || echo '0' )" >> $GITHUB_OUTPUT
      
      - name: Increment tag
        id: increment_tag
        run: |
          TAG=${{ steps.get_tag.outputs.tag }}
          TAG=$((TAG+1))
          echo "new_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Push new tag
        run: |
          git tag ${{ steps.increment_tag.outputs.new_tag }}
          git push origin ${{ steps.increment_tag.outputs.new_tag }}

      - name: Make release with Github
        id: create_release
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "Release ${{ steps.increment_tag.outputs.new_tag }}",
              tag_name: "${{ steps.increment_tag.outputs.new_tag }}"
            })
      
