name: CD for EMTC

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release Tasks
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Get latest tag
        id: get_tag
        run: |
          echo "tag=$(git describe --abbrev=0 --tags 2>/dev/null || echo '0' )" >> $GITHUB_OUTPUT
      
      - name: Increment tag
        id: increment_tag
        run: |
          TAG=${{ steps.get_tag.outputs.tag }}
          TAG=$((TAG+1))
          echo "new_tag=$TAG" >> $GITHUB_OUTPUT
      
      - name: Push new tag
        run: |
          git tag ${{ steps.increment_tag.outputs.new_tag }}
          git push origin ${{ steps.increment_tag.outputs.new_tag }}
      
      - name: Make release with Github CLI
        run: |
          gh release create {{ steps.increment_tag.outputs.new_tag }} -t {{ steps.increment_tag.outputs.new_tag }} --generate-notes