name: Convert DOCX to Markdown

on:
  push:
    paths:
      - "upload_posts/*.docx"  # Runs only when a .docx file is added to upload_posts/

jobs:
  convert-docx-to-md:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc and Unzip
        run: sudo apt-get install -y pandoc unzip

      - name: Ensure necessary folders exist
        run: |
          mkdir -p _posts/
          mkdir -p img/
          mkdir -p upload_posts/completed/

      - name: Convert DOCX to Markdown
        run: |
          for file in upload_posts/*.docx; do
            [ -e "$file" ] || continue
            filename=$(basename -- "$file" .docx)

            # Extract images from DOCX
            unzip -o "$file" -d "extracted/"
            if [ -d "extracted/word/media" ]; then
              mv extracted/word/media/* img/ || true
            fi

            # Convert DOCX to GitHub-Flavored Markdown (GFM) and extract media
            echo "RUNNING PANDOC"
            pandoc "$file" --wrap=none -t gfm --extract-media=img -o "temp.md"

            # Extract the date and title from YAML
            echo "EXTRACTING DATE AND TITLE FROM YAML"
            post_date=$(grep "^date:" temp.md | awk '{print $2}')
            post_title=$(grep "^title:" temp.md | sed 's/title: //' | tr -d '"')

            # Format the filename as YYYY-MM-DD-title.markdown
            echo "FORMATTING FILENAME"
            formatted_title=$(echo "$post_title" | tr ' ' '-' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]//g')
            new_filename="${post_date}-${formatted_title}.markdown"
           
            # Fix image paths in Markdown to use /img/
            echo "FIXING IMG PATH IN MARKDOWN USING SED"
            sed -i 's#!\[\(.*\)\](img/word/media/#![\1](/img/#g' temp.md

            # Move the correctly named file to _posts/
            echo "MOVING FILE WITH CORRECT FILENAME"
            mv temp.md "_posts/${new_filename}"

            # Move processed DOCX file to completed folder
            echo "MOVING COMPLETED FILE"
            mv "$file" "upload_posts/completed/${filename}.docx"
          done

      - name: Commit and push new Markdown files
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add _posts/*.markdown img/* upload_posts/completed/*.docx
          git commit -m "Converted DOCX to Markdown and moved images"
          git push
        continue-on-error: true  # Prevent failure if no new files are added
