name: "Update Newsletter"

on:
    push:
        paths:
            'assets/Newsletters/*.pdf'

jobs:
    update-newsletter:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Get changed file
              id: changed_files
              uses: tj-actions/changed-files@v45

            - name: List all changed files
              env:
                ALL_ADDED_FILES: ${{ steps.changed_files.outputs.added_files }}
              run: |
                echo $ALL_ADDED_FILES

            - name: Update and push change to header.html
              env:
                ALL_ADDED_FILES: ${{ steps.changed_files.outputs.added_files }}
              run: |
                sed -E -i "s|assets/Newsletters/[^\"]+|$ALL_ADDED_FILES|g" _includes/header.html
                git add .
                git commit -m "updating header with NL name"
                git push