name: "Update Newsletter"

on:
    push:
        paths:
            'assets/Newsletters/*.pdf'

jobs:
    update-newsletter:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Get changed file
              id: changed_files
              uses: tj-actions/changed-files@v45

            - name: List all changed files
              env:
                ALL_ADDED_FILES: ${{ steps.changed_files.outputs.added_files }}
              run: |
                for file in ${ALL_ADDED_FILES}; do
                  echo "$file"
                done